name: LadderBar
options:
  bundleIdPrefix: com.jordanbrock
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  LadderBar:
    type: application
    platform: macOS
    sources:
      - LadderBar
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jordanbrock.LadderBar
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_FILE: LadderBar/Info.plist
        INFOPLIST_KEY_LSUIElement: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: LadderBar/LadderBar.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: true
        ENABLE_APP_SANDBOX: true
        com.apple.security.network.client: true
